---
title: "Plots_Brain_Thresholds"
author: "HannahSavage"
date: "2023-05-18"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Set env
```{r, include = FALSE}
library(readxl)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(grid)
library(reshape)
library(scales)
library(sjmisc)
library(scatterpie)
library(showtext)
library(psych)
#library('qgraph')
library('data.table')
library('reshape2')
library('ade4')
library('viridis')
library(extrafont)
library(ggalluvial)
 
```

#Define themes
```{r}
##DEFINE THEMES:
#Demographics plot
theme_demographics <- theme_bw() +
  theme(
    aspect.ratio = 1/1,
    panel.grid = element_blank(), #no grid
    panel.border = element_blank(), #no border around the entire plot
    axis.line.x.bottom = element_line(color = 'black'), #bottom border
    axis.line.y.left   = element_line(color = 'black'), #left border
    axis.line.y.right  = element_blank(), #no right border
    axis.text.y.right  = element_blank(),
    #legend.title = element_blank(),
    #legend.position = c(0.9,0.6),
    plot.title = element_text()
  )

```


```{r}
##SET DIAGNOSIS: 
#Diagnosis <- 'ADHD'
#Diagnosis <- 'ARD'
#Diagnosis <- 'ASD'
#Diagnosis <- 'BP'
#Diagnosis <- 'BDD' ##NO STUDIES
#Diagnosis <- 'BPD'
#Diagnosis <- 'GD'
#Diagnosis <- 'MDD'
#Diagnosis <- 'OCD'
#Diagnosis <- 'Schizophrenia'
Diagnosis <- 'SUD' 
```


```{r}
#LOAD THE CLINICAL SAMPLE
Regions_Activated <- read_csv(paste0("M:/Documents/Hariri_review/USE_ME/Activations/Patients/Regions_Activated_", Diagnosis,".csv"), show_col_types = FALSE)
Regions_Activated <- Regions_Activated[-c(1)]
```

```{r}
#cols_to_plot_searched <- c("Th1_Searched", "Th2_Searched", "Th3_Searched", "Th4_Searched")
#cols_to_plot_activated <- c("Th1_Activated","Th2_Activated", "Th3_Activated", "Th4_Activated","Th5_Activated","Th6_Activated", "Th7_Activated", "Th8_Activated", "Th9_Activated")
#cols_to_plot_applied <-  c("Th5_Applied","Th6_Applied", "Th7_Applied", "Th8_Applied", "Th9_Applied")

#MaxVals <- as.data.frame(subset(Regions_Activated[-c(1)] %>% select(all_of(cols_to_plot_activated))))
#MaxVals$MAX <- apply(MaxVals, 1, max, na.rm=TRUE)
```

#For plotting only 6 thresholds
```{r}
cols_to_plot_searched <- c("Th1_Searched", "Th2_Searched", "Th3_Searched")
cols_to_plot_activated <- c("Th1_Activated","Th2_Activated", "Th3_Activated","Th5_Activated","Th6_Activated", "Th7_Activated")
cols_to_plot_applied <-  c("Th5_Applied","Th6_Applied", "Th7_Applied")

MaxVals <- as.data.frame(subset(Regions_Activated[-c(1)] %>% select(all_of(cols_to_plot_activated))))
MaxVals$MAX <- apply(MaxVals, 1, max, na.rm=TRUE)
```

```{r}
Regions_Activated <- Regions_Activated[rowSums(Regions_Activated[-c(1)])>0,]
#Regions_Activated <- pivot_longer(Regions_Activated, !Region, names_to = "Thresh_Act", values_to = "Count")
#Regions_Activated <- filter(Regions_Activated, Count > 1)
#Regions_Activated <- pivot_wider(Regions_Activated, !Region, names_from = "Thresh_Act", values_from = "Count")

```


```{r}


REGIONS <- Regions_Activated$Region

if (Diagnosis == 'ADHD') {
  Regions_Activated$Th7_Applied <- 2
} else if (Diagnosis == 'ARD') {
  Regions_Activated$Th5_Applied <- 7
  Regions_Activated$Th7_Applied <- 11
} else if (Diagnosis == 'ASD') {
  Regions_Activated$Th5_Applied <- 1
#} else if (Diagnosis == 'BDD') {
  #Regions_Activated$Th7_Applied <- 1
#BPD No >Th5
} else if (Diagnosis == 'BP') {
  Regions_Activated$Th7_Applied <- 8
} else if (Diagnosis == 'BPD') {
  Regions_Activated$Th7_Applied <- 0 #place filler
} else if (Diagnosis == 'GD') {
  Regions_Activated$Th7_Applied <- 1
} else if (Diagnosis == 'MDD') {
  Regions_Activated$Th5_Applied <- 4
  Regions_Activated$Th7_Applied <- 15
} else if (Diagnosis == 'OCD') {
  Regions_Activated$Th5_Applied <- 7
  Regions_Activated$Th7_Applied <- 2
} else if (Diagnosis == 'Schizophrenia') {
  Regions_Activated$Th6_Applied <- 1
} else if (Diagnosis == 'SUD') {
  Regions_Activated$Th5_Applied <- 1
  Regions_Activated$Th7_Applied <- 2
}

#REGIONS = "NOSIGDIF"  

for (r in REGIONS){
#Subcortical - clockwise
  if (r == "Amygdala"){ROIfill <- c("#ac0066", "#E6B2D1", "white")}
  if (r == "Thalamus"){ROIfill <- c("#ec008c", "#f982dc", "white")}
  if (r == "Hypothalamus"){ROIfill <- c("#ff6699", "#FFD1E0", "white")}
  if (r == "Basal_Ganglia"){ROIfill <- c("#ff9fbf", "#FFE2EC", "white")}
  if (r == "Parahippocampus"){ROIfill <- c("#fd8c94", "#FEDCDE", "white")}
  if (r == "Hippocampus"){ROIfill <- c("#ff9966", "#FFE0D1", "white")}
  
#Parietal-Cerebellum/Brainstem - clockwise
  if (r == "Parietal_Superior"){ROIfill <- c("#122da6", "#B7C0E4", "white")}
  if (r == "Parietal_Inferior"){ROIfill <- c("#1100ff", "#B7B2FF", "white")}
  if (r == "Cerebellum"){ROIfill <- c("#1ebbd7", "#BBEAF3", "white")}
  if (r == "Brain_stem"){ROIfill <- c("#40e8ec", "#C5F8F9", "white")}
  if (r == "Parietal_Precuneus"){ROIfill <- c("#00bfff", "#B2ECFF", "white")}

#Temporal - clockwise
  if (r == "Temporal_Superior"){ROIfill <- c("#008154", "#B2D9CB", "white")}
  if (r == "Temporal_Inferior"){ROIfill <- c("#48bf91", "#C8ECDE", "white")}
  if (r == "Fusiform"){ROIfill <- c("#56e78e", "#CCF8DD", "white")}
  if (r == "Insula"){ROIfill <- c("#8affa0", "#DCFFE2", "white")}
  if (r == "Temporal_Inferior"){ROIfill <- c("#97d5bf", "#E0F2EC", "white")}
  if (r == "Temporal_Middle"){ROIfill <- c("#58b6a6", "#CDE9E4", "white")}

#Frontal - clockwise
  if (r == "Cingulate"){ROIfill <- c("#5a0082", "#CDB2D9", "white")}
  if (r == "Frontal_dmPFC"){ROIfill <- c("#8800c7", "#DBB2EE", "white")}
  if (r == "Frontal_vmPFC"){ROIfill <- c("#c469fc", "#EDD2FE", "white")}
  if (r == "Orbito_Frontal_TOTAL"){ROIfill <- c("#c345d5", "#EEC7F2", "white")}
  if (r == "Frontal_vlPFC"){ROIfill <- c("#da85e3", "#F4DAF7", "white")}
  if (r == "Frontal_dlPFC"){ROIfill <- c("#d1b2e0", "#F1E8F6", "white")}

#Occipital - clockwise
  if (r == "Occipital_V1"){ROIfill <- c("#c31738", "#EDB9C3", "white")}
  if (r == "Occipital_Secondary"){ROIfill <- c("#db5734", "#F4CCC2", "white")}
  if (r == "Lingual"){ROIfill <- c("#eb8838", "#F9DBC3", "white")}
  if (r == "Occipital_Cuneus"){ROIfill <- c("#f4b74a", "#FCE9C8", "white")}
  
  #NSD
  if (r == "NOSIGDIF"){ROIfill <- c("black", "lightgrey", "white")}
 
  
  
  #else {ROIfill <- c( "#ac0066", "#F2D6E6", "white")}
  df_A <- as.data.frame(t(as.data.frame(subset(Regions_Activated, Region == r) %>% select(all_of(cols_to_plot_activated)))))
  df_S <- as.data.frame(t(as.data.frame(subset(Regions_Activated, Region == r) %>% select(all_of(cols_to_plot_searched)))))
  df_WB <- as.data.frame(t(as.data.frame(subset(Regions_Activated, Region == r) %>% select(all_of(cols_to_plot_applied)))))
  
  showtext::showtext_opts(dpi = 200)
  
  PLOT <- ggplot() + 
      geom_bar(df_S, mapping = aes(x = factor(1:nrow(df_S)), y = df_S[,1], fill = ROIfill[2]), stat = "identity", width = 0.75)+
      geom_bar(df_WB, mapping = aes(x = factor((1:nrow(df_WB)+3)), y = df_WB[,1], fill = ROIfill[3]), colour = ROIfill[2],  linewidth = 1.5, stat = "identity", width=0.75)+
      geom_bar(df_A, mapping = aes(x = factor(1:nrow(df_A)), y = df_A[,1], fill = ROIfill[1]), stat = "identity", width=0.5)+
      labs(x = "Threshold", y = "Number of reports", family = "Calibri Light" )+
      scale_x_discrete(labels=c("ROI 1", "ROI 2", "ROI 3", "WB 1",  "WB 2", "WB 3",  "WB 4"))+ #rownames(df_A)
      #scale_x_discrete(labels=c("ROI 1", "ROI 2", "ROI 3", "ROI 4", "WB 5",  "WB 6", "WB 7",  "WB 8",  "WB 9"))+ #rownames(df_A)
      ylim(0,30)+
      scale_fill_manual(values=ROIfill)+
      #ggtitle(r) +
      theme(panel.grid = element_blank(), #no grid
            panel.border = element_blank(), #no border around the entire plot
            axis.line.x.bottom = element_line(color = 'black'), #bottom border
            axis.line.y.left   = element_line(color = 'black'), #left border
            axis.line.y.right  = element_blank(), #no right border
            #legend.title = element_blank(),
            legend.position = "none",
            panel.background = element_rect(fill = "white"),
            aspect.ratio = 1/1,
            axis.text.x = element_text(angle = 0),
            text=element_text(size=12, 
            family="Calibri Light"))
  ggsave(PLOT, filename = paste0("M:/Documents/Hariri_review/USE_ME/Activations/Patients/",Diagnosis,"_Plots/",Diagnosis,"_",r,"_6_withWBborder.png"))
    
  
print(PLOT)
dev.off()
}

```

