---
title: "Scanner_plots"
author: "HannahSavage"
date: "2023-08-21"
output: html_document
---

## SET ENV
```{r setup, include=FALSE}
library(readxl)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(reshape)
library(scales)
library(sjmisc)
library(scatterpie)
library(showtext)
library(psych)
library(tidyr)

library(cowplot)
```

```{r Define_Themes}
##DEFINE THEMES:
theme_task_names <- theme_bw() +
  theme(
    panel.grid = element_blank(),
    axis.text = element_blank(),
    axis.title = element_blank(),
    axis.ticks = element_blank(),
    panel.border = element_blank(),
    legend.title = element_blank(),
    plot.title = element_text( hjust = 0.5 )
  )

```

#Import the Data Extraction table:
```{r}
Extracted_data <- read_excel("M:/Documents/Hariri_review/USE_ME/Data_extraction_CLEANING.xlsx")
#Extracted_data <- read_excel("M:/Documents/Hariri_review/Data_extraction_CLEANING.xlsx")
#View(Extracted_data)
```
```{r}
#How many articles
Num_articles <- unique(round(Extracted_data$`Article_Num`))
Total_num_articles <- length(Num_articles)
Total_num_articles 
```

```{r}
Scanner_data <- Extracted_data[,c("Article_Num", "First_Author", "Publication_Year", "MRI_Scanner_STANDARDISED")]


# Step 1: Transform Scanner_data into brand_counts format
Scanner_data <- Scanner_data %>%
    mutate(MRI_Scanner_STANDARDISED = strsplit(MRI_Scanner_STANDARDISED, "; ")) %>%
    unnest(MRI_Scanner_STANDARDISED) %>%
  mutate(BRAND = sub("^(GE|Siemens|Philips|Bruker).*", "\\1", MRI_Scanner_STANDARDISED),
         DETAILS = sub("^(?:GE|Siemens|Philips|Bruker)\\s*(.*)", "\\1", MRI_Scanner_STANDARDISED)) %>%
  count(BRAND, DETAILS) %>%
  mutate(Total = sum(n),
         Percentage = (n / Total) * 100)


Scan_table <- Scanner_data[,c("BRAND", "DETAILS", "n")]

Scanner_name_count <- Scanner_data[,c("BRAND", "DETAILS", "n", "Percentage")]# "Scanner_Name")]
Scanner_name_count[5] <- "1"
names(Scanner_name_count)[3] <- "Count_of_studies"
names(Scanner_name_count)[4] <- "Percentage_of_studies"
names(Scanner_name_count)[5] <- "Scanner_Name"

Total_scan <- as.numeric(sum(Scanner_name_count$Count_of_studies))
sum_total_scan = sum(Scanner_name_count$Count_of_studies)

```

```{r}
Scan_table <- Scan_table%>%
    arrange(match(BRAND, c("Siemens", "GE", "Philips", "Bruker", "NA")))#, desc(DETAILS), desc(n))

Scan_table$DETAILS[1] <- "SiemensNA"
Scan_table$DETAILS[10] <- "GENA"
Scan_table$DETAILS[23] <- "PhilipsNA"

firstLevel = Scan_table %>% summarize(Total_scan = sum(n))
num_uniq = length(Scan_table$DETAILS) 

gov_pop = Scan_table %>% group_by(BRAND) %>%
  summarize(Total_scan = sum(n)) %>%
  arrange(match(BRAND, c("Siemens", "GE", "Philips", "Bruker", "NA")))

gov_pop2 = Scan_table %>% group_by(DETAILS) %>%
  summarize(Total_scan = sum(n)) %>%
 arrange(match(DETAILS, Scan_table$DETAILS))


compute_angle = function(perc){
  angle = -1
  if(perc < 0.25) # 1st q [90,0]
    angle = 90 - (perc/0.25) * 90
  else if(perc < 0.5) # 2nd q [0, -90]
    angle = (perc-0.25) / 0.25 * -90
  else if(perc < 0.75) # 3rd q [90, 0]
   angle = 90 - ((perc-0.5) / 0.25 * 90)
  else if(perc < 1.00) # last q [0, -90]
    angle = ((perc -0.75)/0.25) * -90
# Or even more compact, but less readable
  if(perc < 0.5) # 1st half [90, -90]
    angle = (180 - (perc/0.5) * 180) - 90
  else # 2nd half [90, -90]
    angle = (90 - ((perc - 0.5)/0.5) * 180)
  return(angle)
}

secondLevel = gov_pop %>%
  mutate(running=cumsum(Total_scan), pos=running - Total_scan/2) %>% group_by(1:n()) %>% # to compute row by row
  mutate(angle=compute_angle((running - Total_scan/2) / sum_total_scan))


thirdLevel = gov_pop2 %>% 
  arrange(match(DETAILS, Scan_table$DETAILS)) %>%
  mutate(running=cumsum(Total_scan), pos=running - Total_scan/2) %>% group_by(1:n()) %>% # to compute row by row
  mutate(angle=compute_angle((running - Total_scan/2) / sum_total_scan))

```

```{r}

brand_colors <- c("#ec008c", "#40e8ec", "#56e78e", "#c345d5",'white')
#c("Siemens", "GE", "Philips", "Bruker", "NA"))) BACKWARDS


#PLOT OF SCANNER BRANDS
sunburst_SCANNERS1 =
  ggplot(firstLevel) +
  geom_bar(data=firstLevel, aes(x=-0.5, y=Total_scan:Total_scan), fill='white', stat='identity', width=1.1) +
  geom_bar(data=firstLevel, aes(x=0, y=Total_scan:Total_scan), fill='white', stat='identity', width=1) +
  
 # geom_bar(data=gov_pop, 
#          aes(x = 0, y = Total_scan, fill = "white"),
#          colour = 'white', position = 'stack', stat = 'identity', size = 0.6)+
  
  geom_bar(data=secondLevel, 
          aes(x = 1, y = Total_scan,  fill = reorder(BRAND, desc(Total_scan))), 
          colour = 'white', position = 'stack', stat = 'identity', size = 0.6)+
          scale_fill_manual(values = brand_colors)+
    
  coord_polar('y') + 
  theme_task_names +
  theme(legend.position = "none")

sunburst_SCANNERS1


#PLOT OF SCANNER DETAILS
details_colors <- c("#F2F4F4", "#E6B2D1", "#ec008c", "#F9B2DC", "#ff6699", "#FFD1E0", "#ff9fbf", "#FFE2EC", "#fd8c94", ##SIEMENS
                    "#F2F4F4","#1ebbd7", "#00689e", "#40e8ec", "#0099b8", "#00bfff", "#005f88", "#BBEAF3", "#3397af", "#C5F8F9", "#008aad", "#B2ECFF", "#007499", #GE
                    "#F2F4F4", "#56e78e", "#CCF8DD", "#8affa0", "#48bf91", #Philips
                    "#c469fc", "#EDD2FE",#Bruker
                    "white") 


sunburst_SCANNERS2 =
  ggplot(firstLevel) +
  geom_bar(data=firstLevel, aes(x=-0.5, y=Total_scan:Total_scan), fill='white', stat='identity', width=1.1) +
  geom_bar(data=firstLevel, aes(x=0, y=Total_scan:Total_scan), fill='white', stat='identity', width=1) +

  geom_bar(data=thirdLevel, 
          aes(x = 2, y = Total_scan, fill = reorder(DETAILS, match(DETAILS, Scan_table$DETAILS) )), 
          colour = 'white', position = 'stack', stat = 'identity', size = 0.6)+
          scale_fill_manual(values = details_colors)+
  
   #geom_bar(data=secondLevel,
  #  aes(x=1, y=Total_scan, fill =BRAND),
  # position='stack', stat='identity') +
    
  coord_polar('y') + 
  theme_task_names #+
  #theme(legend.position = "none")

sunburst_SCANNERS2

#COMBINED
overlayed_plot <- plot_grid(sunburst_SCANNERS1, sunburst_SCANNERS2, align = "v")

options(repr.plot.width = 10, repr.plot.height = 10)
overlayed_plot 
  
```



```{r}
# Assuming you have a dataframe named 'reordered_data'
sum_percentages_by_brand <- Scanner_data %>%
  group_by(BRAND) %>%
  summarize(Sum_Percentage = sum(Percentage))

# Print the results to the terminal
print(sum_percentages_by_brand)
```


